[package]
name="001_average"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[build.boogie]
timeout=10

[check]
min=-3
max=3
length=3
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

