[package]
name="010_sort"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-2
max=2
length=3
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

