[package]
name="016_date"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie2"]

[build.whiley]
source="/"

[check]
min=-5
max=5
length=3
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
