[package]
name="008_scc"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=0
max=1
length=1
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
