[package]
name="008_scc"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[build.boogie]
timeout=120

[check]
min=0
max=1
length=1
depth=2
ignores=["main"]

[dependencies]
std="0.3.1"
