[package]
name="032_arrlist"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-3
max=3
length=3
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

