[package]
name="018_heap"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-1
max=2
length=4
depth=1
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
std="0.2.12"
