[package]
name="018_heap"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-2
max=2
length=3
depth=1

[dependencies]
wybenchparser="1.0.0"
std="0.2.11"
