[package]
name="013_btree"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-2
max=2
length=3
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

