[package]
name="015_cashtill"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie2"]

[build.whiley]
source="/"

[check]
min=-3
max=3
length=2
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"