[package]
name="102_conway"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=2
max=4
length=4
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
