[package]
name="012_cyclic"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-2
max=2
length=2
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

