[package]
name="006_queens"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-2
max=2
length=3
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
std="0.2.12"
