[package]
name="028_flag"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-3
max=3
length=3
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

