[package]
name="004_matrix"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-1
max=1
length=3
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
std="0.2.12"
