[package]
name="004_matrix"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[build.boogie]
timeout=60

[check]
min=-1
max=1
length=3

[dependencies]
wybenchparser="1.0.0"
