[package]
name="030_fracions"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-3
max=3
length=3
depth=1
ignores=["main"]

[dependencies]
std="0.3.1"

