[package]
name="022_cars"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie2"]

[build.whiley]
source="/"

[check]
min=-3
max=3
length=3
depth=1
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
