[package]
name="011_codejam"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-1
max=1
length=2
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

