[package]
name="011_codejam"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-4
max=4
length=4
depth=3
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
std="0.2.12"
